columnSuffix: eubcgrjm
contentColumnType: text
fieldGroup: 8a6541e9-9801-412b-8e87-19805dc61004 # Team Members
handle: phoneNumber
instructions: 'Add a valid phone number following the pattern `XXX.XXX.XXXX`'
name: 'Phone Number'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: XXX.XXX.XXXX
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
