columnSuffix: qpynjbfl
contentColumnType: text
fieldGroup: 8a6541e9-9801-412b-8e87-19805dc61004 # Team Members
handle: positionTitle
instructions: 'The team member''s employment role or title.'
name: 'Position Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
