columnSuffix: ipxklvkg
contentColumnType: text
fieldGroup: a20083a2-fbdf-4122-ab77-401551ba0496 # Assets
handle: squareImageTransform
instructions: null
name: 'Square Image Transform'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '992'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
